#!/bin/bash

CWD=`pwd -P`
TEMP=$CWD/lib/template
ARG=$1

# compile user source
terffee -c ${CWD}/lib/src/view -o ${CWD}/lib/js/view -c ${CWD}/lib/src/control -o ${CWD}/lib/js/control

# watch user source
if [ "$ARG" == "-w" ]; then
  terffee -w -c ${CWD}/lib/src/view -o ${CWD}/lib/js/view -c ${CWD}/lib/src/control -o ${CWD}/lib/js/control
fi

